source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AloomaIosSDK_Example', :exclusive => true do
  pod "AloomaIosSDK", :path => "../"
end

target 'AloomaIosSDK_Tests', :exclusive => true do
  pod "AloomaIosSDK", :path => "../"

  
end
