target "HelloMixpanelTests" do
    pod 'CocoaHTTPServer'
end

target "ABTestingTests" do
    pod 'CocoaHTTPServer'
end

target "EventBindingTests" do
    pod 'OCMock', '~> 3.0'
end

target "HelloMixpanel_tvOSTests" do
    pod 'CocoaLumberjack'
end
