use_frameworks!

def shared_pods
    pod 'OCMock', '~> 3.0'
    pod 'Nocilla'
end

target :HelloMixpanelTests do
  platform :ios, '8.0'
  shared_pods
end

target :HelloMixpanel_tvOSTests do
  platform :tvos, '9.0'
  shared_pods
end
